"""
TEARDOWN — Google Analytics 4 injection. Imported by build.py.

Set GA4_MEASUREMENT_ID in build.py (or TEARDOWN_GA4_ID in the environment) and
every page gets the tag. Leave it empty and every page gets nothing: no script,
no cookies, no consent banner. There is no half-configured state.

Three things this does that a copy-pasted GA snippet does not:

1. CONSENT MODE V2, DENIED BY DEFAULT. GA4 sets cookies, which in the EU and UK
   needs consent before it happens, not after. Consent defaults to denied, the
   banner grants it, and the choice persists. Declining is a real decline: the
   tag stays loaded but never gets storage consent, so no analytics cookie is
   written.

2. NO HITS FROM LOCALHOST. Development traffic in your production property is
   noise you cannot retroactively remove.

3. RESPECTS Do Not Track. Cheap to honour, and a site whose pitch is
   independence should.

The block is written between <!-- GA4:start --> and <!-- GA4:end --> markers so
it is idempotent: rebuilding replaces it rather than stacking copies.
"""

import re
from pathlib import Path

START = "<!-- GA4:start generated by build.py -->"
END = "<!-- GA4:end -->"
BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)


def _snippet(measurement_id):
    return f"""{START}
<script async src="https://www.googletagmanager.com/gtag/js?id={measurement_id}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){{ dataLayer.push(arguments); }}
  window.gtag = gtag;

  var TD_GA_ID = '{measurement_id}';
  var TD_CONSENT_KEY = 'td-consent';

  /* Consent Mode v2. Denied until the reader says otherwise. This has to run
     before config, or the first page_view is sent with storage granted. */
  gtag('consent', 'default', {{
    ad_storage: 'denied',
    ad_user_data: 'denied',
    ad_personalization: 'denied',
    analytics_storage: 'denied',
    wait_for_update: 500
  }});

  gtag('js', new Date());

  /* Local and preview hosts never report. Dev traffic in a production property
     cannot be removed afterwards. */
  var TD_LOCAL = /^(localhost|127\\.0\\.0\\.1|\\[::1\\])$/.test(location.hostname)
              || location.protocol === 'file:';
  var TD_DNT = navigator.doNotTrack === '1' || window.doNotTrack === '1';

  gtag('config', TD_GA_ID, {{
    send_page_view: !TD_LOCAL && !TD_DNT,
    anonymize_ip: true
  }});

  (function () {{
    var stored = null;
    try {{ stored = localStorage.getItem(TD_CONSENT_KEY); }} catch (e) {{}}

    function grant(granted) {{
      gtag('consent', 'update', {{
        analytics_storage: granted ? 'granted' : 'denied'
      }});
    }}

    if (stored === 'granted') {{ grant(true); return; }}
    if (stored === 'denied')  {{ grant(false); return; }}
    if (TD_LOCAL || TD_DNT)   {{ grant(false); return; }}

    /* No stored choice: ask. Built after load so it never blocks paint. */
    document.addEventListener('DOMContentLoaded', function () {{
      var bar = document.createElement('div');
      bar.className = 'consent';
      bar.setAttribute('role', 'dialog');
      bar.setAttribute('aria-label', 'Analytics consent');
      bar.innerHTML =
        '<p class="consent__text">This site uses Google Analytics to count '
        + 'visits. Nothing is shared with advertisers. Decline and no analytics '
        + 'cookie is set.</p>'
        + '<div class="consent__actions">'
        + '<button type="button" class="consent__btn" data-consent="denied">Decline</button>'
        + '<button type="button" class="consent__btn consent__btn--yes" data-consent="granted">Allow</button>'
        + '</div>';

      bar.addEventListener('click', function (e) {{
        var btn = e.target.closest('[data-consent]');
        if (!btn) return;
        var choice = btn.getAttribute('data-consent');
        try {{ localStorage.setItem(TD_CONSENT_KEY, choice); }} catch (err) {{}}
        grant(choice === 'granted');
        bar.remove();
      }});

      document.body.appendChild(bar);
    }});
  }})();
</script>
{END}"""


def run(root, measurement_id):
    """Add, refresh or remove the GA4 block on every page. Returns pages touched."""
    root = Path(root)
    block = _snippet(measurement_id) if measurement_id else ""
    touched = []

    for path in list(root.glob("*.html")) + list(root.glob("posts/*.html")):
        html = original = path.read_text(encoding="utf-8")

        if BLOCK_RE.search(html):
            html = BLOCK_RE.sub(lambda _: block, html)
            if not measurement_id:
                html = re.sub(r"\n{3,}", "\n\n", html)
        elif block:
            html = html.replace("</head>", block + "\n</head>", 1)

        if html != original:
            path.write_text(html, encoding="utf-8")
            touched.append(path.name)

    return touched
